Chapter 22
# 利用pandas.merge() 完成合并
Book_1《编程不难》 | 鸢尾花书：从加减乘除到机器学习

In [1]:
import pandas as pd

In [2]:
df_left  = pd.DataFrame({'X': ['a', 'b', 'c'],
                         'M': [1, 2, 3]})
df_left

   X  M
0  a  1
1  b  2
2  c  3

In [3]:
df_right = pd.DataFrame({'X': ['b', 'c', 'd'],
                         'N': [5, 6, 7]})
df_right

   X  N
0  b  5
1  c  6
2  d  7

In [4]:
pd.merge(df_left, df_right, on = 'X', how = 'left')
# 与X列为准；找出相同的值bc; how=left--以df_left为基准

   X  M    N
0  a  1  NaN
1  b  2  5.0
2  c  3  6.0

In [6]:
pd.merge(df_left, df_right, on = 'X', how = 'right')
# 与X列为准；找出相同的值bc; how=right--以df_right为基准

   X    M  N
0  b  2.0  5
1  c  3.0  6
2  d  NaN  7

In [7]:
df_right = pd.DataFrame({'X': ['b', 'c', 'd'],
                         'M': [5, 6, 7]})
df_right

   X  M
0  b  5
1  c  6
2  d  7

In [8]:
pd.merge(df_left, df_right, on = 'X', how = 'left')

   X  M_x  M_y
0  a    1  NaN
1  b    2  5.0
2  c    3  6.0

In [9]:
df_left  = pd.DataFrame({'X': ['a', 'b', 'c'],
                         'M': [1, 2, 3]})
df_left

   X  M
0  a  1
1  b  2
2  c  3

In [10]:
df_right = pd.DataFrame({'Y': ['b', 'c', 'd'],
                         'N': [5, 6, 7]})
df_right

   Y  N
0  b  5
1  c  6
2  d  7

In [ ]:
pd.merge(df_left, df_right, left_on = 'X', right_on = 'Y', how = 'left')

   X  M    Y    N
0  a  1  NaN  NaN
1  b  2    b  5.0
2  c  3    c  6.0

In [11]:
pd.merge(df_left, df_right, left_on = 'X', right_on = 'Y', how = 'right')

     X    M  Y  N
0    b  2.0  b  5
1    c  3.0  c  6
2  NaN  NaN  d  7

In [12]:
pd.merge(df_left, df_right, left_on = 'X', right_on = 'Y', how = 'inner')

   X  M  Y  N
0  b  2  b  5
1  c  3  c  6

In [13]:
pd.merge(df_left, df_right, left_on = 'X', right_on = 'Y', how = 'outer')
# 将 how = 'left'与 how = 'right'的数据帧结合起来

     X    M    Y    N
0    a  1.0  NaN  NaN
1    b  2.0    b  5.0
2    c  3.0    c  6.0
3  NaN  NaN    d  7.0