Chapter 22
# 利用stack() 将宽格式转换为长格式
Book_1《编程不难》 | 鸢尾花书：从加减乘除到机器学习

In [1]:
import pandas as pd
import numpy as np

In [2]:
student_ids = [1, 2, 3, 4]
subjects = ['Art', 'Math', 'Science']
np.random.seed(0)
# 使用随机数生成成绩数据
scores = np.random.randint(3, 6,
            size=(len(student_ids),len(subjects)))

In [3]:
# 创建数据帧
df = pd.DataFrame(scores, index=student_ids,
                  columns=subjects)
df

   Art  Math  Science
1    3     4        3
2    4     4        5
3    3     5        3
4    3     3        5

In [4]:
df.columns.names

FrozenList([None])

In [5]:
df.index.names

FrozenList([None])

In [6]:
df.index

Index([1, 2, 3, 4], dtype='int64')

In [7]:
df.columns

Index(['Art', 'Math', 'Science'], dtype='object')

In [8]:
# 修改行列名称
df.columns.names = ['Subject']
df.index.names = ['Student ID']
df

Subject     Art  Math  Science
Student ID
1             3     4        3
2             4     4        5
3             3     5        3
4             3     3        5

In [9]:
df.stack()  # 将Subject转为行

Student ID  Subject
1           Art        3
            Math       4
            Science    3
2           Art        4
            Math       4
            Science    5
3           Art        3
            Math       5
            Science    3
4           Art        3
            Math       3
            Science    5
dtype: int64

In [11]:
df.stack().reset_index()  # 将行索引转为列索引

    Student ID  Subject  0
0            1      Art  3
1            1     Math  4
2            1  Science  3
3            2      Art  4
4            2     Math  4
5            2  Science  5
6            3      Art  3
7            3     Math  5
8            3  Science  3
9            4      Art  3
10           4     Math  3
11           4  Science  5

In [14]:
# 将长格式转化为宽格式
df.stack().reset_index().rename(columns={0: 'Final'}) # 将0重命名为Final

    Student ID  Subject  Final
0            1      Art      3
1            1     Math      4
2            1  Science      3
3            2      Art      4
4            2     Math      4
5            2  Science      5
6            3      Art      3
7            3     Math      5
8            3  Science      3
9            4      Art      3
10           4     Math      3
11           4  Science      5