Chapter 22
# 鸢尾花数据帧使用apply() 自定义函数，对于特定一列
Book_1《编程不难》 | 鸢尾花书：从加减乘除到机器学习

In [1]:
import seaborn as sns
import pandas as pd

In [2]:
iris_df = sns.load_dataset("iris")
# 从Seaborn中导入鸢尾花数据帧
iris_df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [3]:
# 定义函数将花萼长度映射为等级
def map_fnc(sepal_length):
    if sepal_length < 5:
        return 'D'
    elif 5 <= sepal_length < 6:
        return 'C'
    elif 6 <= sepal_length < 7:
        return 'B'
    else:
        return 'A'

利用 apply() 将自定义函数用在数据帧 iris_df['sepal_length'] 上。


apply() 方法可以接受一个函数作为参数，这个函数将会被应用到 DataFrame 的每一行或每
一列上。这个函数可以是 Pandas 中已经定义好的函数，可以是自定义函数，也可以是匿名 lambda
函数。

In [4]:
# 使用 apply 函数将 sepal_length 映射为等级并添加新列
iris_df['ctg'] = iris_df['sepal_length'].apply(map_fnc)
iris_df

     sepal_length  sepal_width  petal_length  petal_width    species ctg
0             5.1          3.5           1.4          0.2     setosa   C
1             4.9          3.0           1.4          0.2     setosa   D
2             4.7          3.2           1.3          0.2     setosa   D
3             4.6          3.1           1.5          0.2     setosa   D
4             5.0          3.6           1.4          0.2     setosa   C
..            ...          ...           ...          ...        ...  ..
145           6.7          3.0           5.2          2.3  virginica   B
146           6.3          2.5           5.0          1.9  virginica   B
147           6.5          3.0           5.2          2.0  virginica   B
148           6.2          3.4           5.4          2.3  virginica   B
149           5.9          3.0           5.1          1.8  virginica   C

[150 rows x 6 columns]