Chapter 22
# 利用merge() 完成左侧独有、右侧独有、全外独有
Book_1《编程不难》 | 鸢尾花书：从加减乘除到机器学习

In [1]:
import pandas as pd

In [2]:
# 创建两个数据帧
left_data = {
    'M': [ 1,   2,   3],
    'X': ['a', 'b', 'c']}
left_df = pd.DataFrame(left_data)
left_df

   M  X
0  1  a
1  2  b
2  3  c

In [3]:
right_data = {
    'X': ['b', 'c', 'd'],
    'N': [ 22,  33,  44]}
right_df = pd.DataFrame(right_data)
right_df

   X   N
0  b  22
1  c  33
2  d  44


首先利用 merge() 完成左连接合并。在 pandas 的 merge() 方法中，
indicator 参数用于指定是否添加一个特殊的列，该列记录了每行的合并方式。
这个特殊的列名可以通过 indicator 参数进行自定义，默认为 "_merge"。"_merge" 列可
以取三个值：
"left_only": 表示该行只在左边的 DataFrame 中存在，即左连接中独有的行。
"right_only": 表示该行只在右边的 DataFrame 中存在，即右连接中独有的行。
"both": 表示该行在两个 DataFrame 中都存在，即连接方式中共有的行。
在
b
中，通过设定筛选条件，left_exl['_merge'] == 'left_only'，我们可以保留合并后
的“左侧独有”行。

In [5]:
# LEFT EXCLUSIVE
left_exl = left_df.merge(right_df,
                         on='X',
                         how='left',
                         indicator=True)

In [6]:
left_exl  #以left数据帧为基准； a为left独有；b c：共有

   M  X     N     _merge
0  1  a   NaN  left_only
1  2  b  22.0       both
2  3  c  33.0       both

In [7]:
left_exl = left_exl[
    left_exl['_merge'] == 'left_only'].drop(
    columns=['_merge'])
left_exl
# 选取 ——merge为left_only的行数据； 删除_merge列

   M  X   N
0  1  a NaN

In [8]:
# RIGHT EXCLUSIVE
right_exl = left_df.merge(right_df,
                          on='X',
                          how='right',
                          indicator=True)

In [9]:
right_exl

     M  X   N      _merge
0  2.0  b  22        both
1  3.0  c  33        both
2  NaN  d  44  right_only

In [10]:
right_exl = right_exl[
    right_exl['_merge'] == 'right_only'].drop(
    columns=['_merge'])
right_exl

    M  X   N
2 NaN  d  44

In [11]:
# FULL OUTER EXCLUSIVE
outer_exl = left_df.merge(right_df,
                          on='X',
                          how='outer',
                          indicator=True)

In [12]:
outer_exl

     M  X     N      _merge
0  1.0  a   NaN   left_only
1  2.0  b  22.0        both
2  3.0  c  33.0        both
3  NaN  d  44.0  right_only

In [13]:
outer_exl = outer_exl[
    outer_exl['_merge'] != 'both'].drop(
    columns=['_merge'])
outer_exl

     M  X     N
0  1.0  a   NaN
3  NaN  d  44.0