Chapter 22
# 利用pivot() 提取学生各科期中考试成绩，学号为行标签，科目为列标签
Book_1《编程不难》 | 鸢尾花书：从加减乘除到机器学习

长格式转换为宽格式：pivot()

In [1]:
import pandas as pd

In [2]:
data = {
    'Student ID':['1','1','2','2','3','3','4','4'],
    'Subject':   ['Math','Art','Science','Art',
                  'Math','Science', 'Art','Math'],
    'Midterm':   [4, 5, 3, 5, 4, 5, 3, 5],
    'Final':     [3, 4, 5, 3, 4, 4, 4, 5]}

In [3]:
df = pd.DataFrame(data)
df

  Student ID  Subject  Midterm  Final
0          1     Math        4      3
1          1      Art        5      4
2          2  Science        3      5
3          2      Art        5      3
4          3     Math        4      4
5          3  Science        5      4
6          4      Art        3      4
7          4     Math        5      5

In [4]:
df.pivot(index='Student ID',
         columns='Subject',
         values='Midterm')

Subject     Art  Math  Science
Student ID
1           5.0   4.0      NaN
2           5.0   NaN      3.0
3           NaN   4.0      5.0
4           3.0   5.0      NaN

In [6]:
df

  Student ID  Subject  Midterm  Final
0          1     Math        4      3
1          1      Art        5      4
2          2  Science        3      5
3          2      Art        5      3
4          3     Math        4      4
5          3  Science        5      4
6          4      Art        3      4
7          4     Math        5      5

In [5]:
df.pivot(index='Student ID',
         columns='Subject',
         values=['Midterm', 'Final'])

# values=['Midterm', 'Final'] 作为列索引

           Midterm              Final
Subject        Art Math Science   Art Math Science
Student ID
1              5.0  4.0     NaN   4.0  3.0     NaN
2              5.0  NaN     3.0   3.0  NaN     5.0
3              NaN  4.0     5.0   NaN  4.0     4.0
4              3.0  5.0     NaN   4.0  5.0     NaN